# Generated by Django 4.0.4 on 2022-04-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_Year',
            fields=[
                ('s_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Clint', models.CharField(max_length=100)),
                ('Position', models.CharField(blank=True, max_length=100, null=True)),
                ('Empsalary', models.IntegerField(blank=True, null=True)),
                ('Billing', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(choices=[('PERMANENT', 'PERMANENT'), ('CONTRACT', 'CONTRACT')], max_length=50)),
                ('Status', models.CharField(choices=[('PAID', 'PAID'), ('Invoiced', 'Invoiced'), ('Offered', 'Offered'), ('Joined', 'Joined'), ('Offer Declined', 'Offer Declined')], max_length=50)),
                ('Invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('Doj', models.DateField(blank=True, null=True)),
                ('Invoiced_on', models.DateField(blank=True, null=True)),
                ('Payment_on', models.DateField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('Collection', models.CharField(blank=True, max_length=100, null=True)),
                ('Recruiter', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Year',
            fields=[
                ('s_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Clint', models.CharField(max_length=100)),
                ('Position', models.CharField(blank=True, max_length=100, null=True)),
                ('Empsalary', models.IntegerField(blank=True, null=True)),
                ('Billing', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(choices=[('PERMANENT', 'PERMANENT'), ('CONTRACT', 'CONTRACT')], max_length=50)),
                ('Status', models.CharField(choices=[('PAID', 'PAID'), ('Invoiced', 'Invoiced'), ('Offered', 'Offered'), ('Joined', 'Joined'), ('Offer Declined', 'Offer Declined')], max_length=50)),
                ('Invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('Doj', models.DateField(blank=True, null=True)),
                ('Invoiced_on', models.DateField(blank=True, null=True)),
                ('Payment_on', models.DateField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('Collection', models.CharField(blank=True, max_length=100, null=True)),
                ('Recruiter', models.CharField(max_length=50)),
            ],
        ),
    ]
